# Generated by Django 4.2.5 on 2023-09-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_tipoproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoProducto',
        ),
    ]
