# Generated by Django 4.2.5 on 2023-09-15 13:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_delete_tipoproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_inventario',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_caducidad',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2023, 9, 15))]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
