# Generated by Django 4.2.5 on 2023-09-15 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_codigo_barras_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(max_length=13, validators=[django.core.validators.MaxValueValidator(13)]),
        ),
    ]
