# Generated by Django 4.2.5 on 2023-09-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_producto_codigo_barras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_inventario',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_caducidad',
            field=models.DateField(verbose_name=models.DateTimeField(auto_now_add=True)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
