# Generated by Django 4.2.5 on 2023-09-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_producto_cantidad_inventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_caducidad',
            field=models.DateTimeField(),
        ),
    ]
